pipeline {
    agent any

    stages {

        stage("Checkout code") {
            steps {
                git branch: 'sarah-feature', url: 'https://github.com/sarah254-tech/React-ToDoList.git'
            }
        }

        stage("Build image and push") {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')
                ]) {

                    sh '''
                        echo "Logging in to DockerHub..."
                        echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin

                        echo "Building backend image..."
                        docker build -t $USERNAME/ci_backend_full_pipeline:v1 -f backend/Dockerfile backend

                        echo "Building frontend image..."
                        docker build -t $USERNAME/ci_frontend_full_pipeline:v1 -f dive-react-app/Dockerfile dive-react-app

                        echo "Pushing images..."
                        docker push $USERNAME/ci_backend_full_pipeline:v1
                        docker push $USERNAME/ci_frontend_full_pipeline:v1
                    '''
                }
            }
        }

        stage("Deploy to EC2") {
            steps {
                withCredentials([
                    sshUserPrivateKey(credentialsId: 'EC2_KEY', keyFileVariable: 'SSH_KEY'),
                    string(credentialsId: 'EC2_HOST', variable: 'EC2_HOST'),
                    usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')
                ]) {

                    sh '''
    chmod 600 $SSH_KEY

    ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@$EC2_HOST << EOF
        echo "Connected to EC2"
        export USERNAME="$USERNAME"
        export PASSWORD="$PASSWORD"
        cd /home/sara/WTF_assignments/React-ToDoList
        bash ~/React-ToDoList/deploy.sh
EOF
'''

                }
            }
        }
    } 
}    


